# Generated by Django 4.2.25 on 2025-10-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=128)),
                ('site', models.CharField(max_length=128)),
                ('study_id', models.CharField(blank=True, max_length=128, null=True)),
                ('batch', models.CharField(blank=True, max_length=128, null=True)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=128)),
                ('site', models.CharField(max_length=128)),
                ('study_id', models.CharField(blank=True, max_length=128, null=True)),
                ('batch', models.CharField(blank=True, max_length=128, null=True)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=128)),
                ('approved_on', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('study', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('site', models.CharField(max_length=128)),
                ('product', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('source_type', models.CharField(default='LDAP', max_length=16)),
                ('added_by', models.CharField(max_length=128)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_instructions', to='reports.draftreport')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=128, null=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='reports.draftreport')),
            ],
        ),
    ]
